parameters:
#    mc_tube_explorer.example.class: MC\TubeExplorerBundle\Example

services:
#    mc_tube_explorer.example:
#        class: %mc_tube_explorer.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
